name: Build and Deploy to Azure App Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        # Needed only during build step
        MONGODB_URI: ${{ secrets.MONGODB_URI }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-app
        path: |
